### ISSUE TITLE
Maintenance: Consider black over yapf as formatter

### ISSUE THREAD

**Issue by heitorlessa** [ran-isenberg/serverless-python-demo#33]
I haven't used `yapf` in ages so please educate me on its advantages over `black`.

My rational is that `black` became an industry standard and doesn't allow custom rules (con depending on where you come from), removing debates about what's readable and what's not (rare occasions you'd need to disable it).

Once we bring in `ruff` as a speedy linter, it'll make it easier to keep both formatter and linter in harmony too: https://beta.ruff.rs/docs/faq/#is-ruff-compatible-with-black

**Comment by ran-isenberg** [comment]
yapf is fast, we use it at work and i had a predefined conf for it. we can change it in favor of ruff if you want

**Comment by heitorlessa** [comment]
Closing as we're using ruff now
